### ISSUE TITLE
Email Signup does not close window on success 

### ISSUE THREAD

**Issue by xorgate** [auth0/Lock.Android#101]
When I sign up using a new email address, I enter new credentials, click the 'sign up' button, and it shows a progress indicator.

In the Auth0 console I can see that the signup was a success, but the app does not seem to recognize, it never leaves the 'in progress' state.

When I hit the backbutton I get back to the login screen, and logging in using the new credentials logs me in perfectly.

**Comment by hzalaz** [comment]
@xorgate will fix it in the next version. In the meantime please use the previous version  (if possible)
