### ISSUE TITLE
Update Google+ social icon

### ISSUE THREAD

**Issue by ritdaw** [auth0/Lock.Android#131]
Icon is outdated, should be as per new Google logo font.

https://materialdesignicons.com/icon/google-plus-box

![google-plus-box](https://cloud.githubusercontent.com/assets/2089152/11090999/a3a356e8-886e-11e5-925c-1225b83e5aff.png)

**Comment by hzalaz** [comment]
The latest version has the updated Logo. We used Google Sign-In logo instead of Google+
