### ISSUE TITLE
Add support for custom social OAuth2 connections

### ISSUE THREAD

**Issue by plusCubed** [auth0/Lock.Android#225]
https://auth0.com/docs/connections/social/oauth2
That was the manual way to add custom OAuth2 connections - recently the Custom Social Connections extension was added to the Auth0 dashboard too.

Right now, Lock shows the custom connection as "Login with OAuth2" (with a generic logo and color), and opens the wrong authorization URL, `connection=oauth2` instead of `connection=[whatever the actual custom connection name is]`.

**Comment by mdumrauf** [comment]
Needing this too
