### ISSUE TITLE
Documentation mismatch between Auth0.com and this Github repository

### ISSUE THREAD

**Issue by vpetkar** [auth0/Lock.Android#249]
https://auth0.com/docs/libraries/lock-android

Does not match with the guide provided on the README.md page on this repository and can use some updating.

Here are some differences

-  Package version number
-  `public class MyApplication extends Application implements LockProvider` is deprecated
- Method for creating Locks and launching the activity

Generally speaking this repository has been correct while the Auth0.com docs are either outdated or wrong.

**Comment by hzalaz** [comment]
Thanks we passed along the feedback to the docs team
