### ISSUE TITLE
How to change LoginActivity strings

### ISSUE THREAD

**Issue by 6franek** [auth0/Lock.Android#262]
I would like to change default LoginActivity strings such as "Login", "Email", "Password" and "Access". I don't see any way to achieve this through theming. How can I achieve this?

**Comment by lbalmaceda** [comment]
Hi @6franek.
If you want to disable "Sign Ups" for a single connection, you can do that in your dashboard: Go to your App's dashboard [DB-Connections](https://manage.auth0.com/#/connections/database) and check _Disable Sign-Ups_. If you want to disable for every connection, you can also do that in the Android SDK by calling `.disableSignUp(true)` in the Lock Builder configuration (check your `Application` class).

For disabling "Reset Password" you can call `.disableChangePassword(true)` as above.
Cheers.

**Comment by lbalmaceda** [comment]
My previous reply was for your initial question. I'll paste it here so that other people can find it if they have the same doubt.

> I would like to hide "Sign up" and "Reset password" buttons in my Android application which uses Lock for Android. Is it possible without creating own UI/Activity for login operation? I've searched in the source code for any parameters which could be passed to the LockActivity, but I couldn't find anything which would work for me.

About your second question of changing Strings in Android-Lock, you'll need to use your own UI. Check [Android CustomUI](https://auth0.com/docs/libraries/lock-android/use-your-own-ui) and [Lock vs CustomUI](https://auth0.com/docs/libraries/when-to-use-lock) --> This is for JS but I'm sure you'll find it useful. 

Cheers.

**Comment by 6franek** [comment]
@lbalmaceda I've changed the first question, because I found out how to do it myself and I didn't want to create a new issue for my other question as this was also related to UI.

@lbalmaceda I've read JavaScript documentation and there is a solution to provide own strings for Lock widget. It's described [here](https://auth0.com/docs/libraries/lock/i18n). 

Is it really not possible to add custom and/or international strings to the Lock widget for Android?

**Comment by lbalmaceda** [comment]
No, there's no way to do this from the Android SDK by today.  Lock searches for string resources using the `R.string.text` way, so it can find the localized version of a string depending on the configured System language. As this file is defined within the library project, you can't change it from the outside. 

If you want to avoid using your own UI, as a workaround you can download the library project (zip) and add it as a _Gradle project dependency_. After that, you'll be able to access the resources that Lock specifies and change them one by one. The only caveat I can think of is that if you want to keep up to date with every library update, you'll need to redo the changes.

**Comment by 6franek** [comment]
Why is it impossible to "override" strings from styles.xml file in the same way it is possible to change eg. icon's style or text size?

**Comment by lbalmaceda** [comment]
@6franek My mistake. 
You can override them using the same resource name in your App's `strings.xml` as the one defined in Lock's [strings.xml](https://github.com/auth0/Lock.Android/blob/master/lock/src/main/res/values/strings.xml) file.
