### ISSUE TITLE
Can't login using social authentication in external browser

### ISSUE THREAD

**Issue by 6franek** [auth0/Lock.Android#278]
I can't login to my application using social authentication in external browser (Chrome). 

When I set `.useWebView(true)` I can login using eg. GitHub account in the WebView displayed inside my app, but when I set it to `.useWebView(false)` GitHub's website is displayed in Chrome and after entering correct login and password and pressing "Sign-in" button, the new website opens with an error (This site can't be reached - ERR_UNKNOWN_URL_SCHEME).

The same error is displayed when I try to login using my Google account too.

**Comment by nikolaseu** [comment]
Hi @6franek, seems like you are missing the android:scheme. See https://github.com/auth0/Lock.Android#install

```xml
<data android:scheme="a0<INSERT_YOUR_APP_CLIENT_ID>" android:host="@string/auth0_domain"/>
```

Also important to remember
> The final value of android:scheme must be in lowercase

**Comment by 6franek** [comment]
@nikolaseu Thanks. The problem was that the value of `android:scheme` contained uppercase characters. Now everything works fine, so the issue can be closed.
