### ISSUE TITLE
getRefreshToken() (2.0.0-beta.2) is null

### ISSUE THREAD

**Issue by ritdaw** [auth0/Lock.Android#304]
When calling getRefreshToken() the returned value is null.
```
        public void onAuthentication(Credentials credentials) {
            Timber.d("OK > " + credentials.getRefreshToken());
        }
```

**Comment by lbalmaceda** [comment]
Hi @ritdaw, what scope are you sending? the default scope for authentication is `openid`. You can change it by setting the authentication parameters using the `withAuthenticationParameters()` method on the builder.

**Comment by ritdaw** [comment]
Ah so we need to pass in scope = openid offline_access.

Apologies, completely overlooked this.
