### ISSUE TITLE
com.auth0.api.APIClientException: Failed to parse JSONP

### ISSUE THREAD

**Issue by paulosuzart** [auth0/Lock.Android#306]
Using version 1.16.1 I got the following exception
```
com.auth0.api.APIClientException: Failed to parse JSONP
at com.auth0.api.internal.ApplicationInfoRequest.onResponse(ApplicationInfoRequest.java:94)
at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
```

The screen shows an alert titled "Failed to load application information", and content "Couldn't obtain application configuration. Please check your Auth0 configurtion and try again."

Any idea? Thank you very much!

**Comment by lbalmaceda** [comment]
Hi @paulosuzart. What `clientId` are you using? > https://manage.auth0.com/#/applications

**Comment by hzalaz** [comment]
Closing this, please use v2 or reopen the issue with more info.
