### ISSUE TITLE
How to use Delegation API with v2?

### ISSUE THREAD

**Issue by sirvon** [auth0/Lock.Android#324]
Thank you for using Lock! Please read the following before creating a new issue.

- [ ] Is this a question about Auth0 in general or a support request? Get in touch with us at https://support.auth0.com.
- [ ] Is this issue something you can fix? Please send us a pull request! Bug fixes are welcome.

Otherwise, create a new issue with the following information:
-------------------------------------------------------------

- [x] Code snippet or sample project that reproduces the bug
```java
        Lock lock = LockContext.getLock(this);
        AuthenticationAPIClient client = lock.getAuthenticationAPIClient();
```

The above methods are unavaliable on v2 of the lib.

**How can I access the Delegation API with this version?**

- [ ] Lock version
**v2**

Make sure to include **as much information as possible** for us to understand and reproduce the bug, that way we can fix it as quickly as possible.

**Comment by hzalaz** [comment]
@sirvon we decoupled the API client from Lock. You can find it here https://github.com/auth0/Auth0.Android#authentication-api
