### ISSUE TITLE
Context instead of Activity

### ISSUE THREAD

**Issue by otomatik** [auth0/Lock.Android#366]
Is there any reason to force passing an activity to the ```build```  method (https://github.com/auth0/Lock.Android/blob/master/lib/src/main/java/com/auth0/android/lock/Lock.java#L202) of the Lock sdk while it seems it's only used as a context afterwards?
Thank you in advance.

**Comment by lbalmaceda** [comment]
Hi @otomatik. 
There was a reason we were using an `Activity` context, I don't recall if that was because we needed a specific `Theme` inheritance, I'll take a look.. What's your use case?

**Comment by otomatik** [comment]
Hi @lbalmaceda thanks for your answer. Just to facilitate testing since it's easier to mock a context than an activity..

**Comment by lbalmaceda** [comment]
@otomatik if that's the case you can use Mockito (mock/when) and Robolectric (buildActivity/setupActivity) to handle those situations. Feel free to check our tests! For now we'll stick to Activity instead of Context. Cheers.
