### ISSUE TITLE
Sending scope with Auth0 object for android lock 2.0.

### ISSUE THREAD

**Issue by sayed19** [auth0/Lock.Android#367]
I am using android sdk version 2. In my project I need to send scope when login to my server using Auth0. How can I successfully do that? I have gone thorough the documentation and found out [this page](https://auth0.com/docs/libraries/lock-android/sending-authentication-parameters). Where It is instructed to use a class 'ParameterBuilder' to set the scope. But how do I assign it to Auth0? I have also noticed the version warning which says "This document is not yet updated to use Lock for Android 2.0. It will be soon!". Now please give me a solution to add scope for login. My deadline for demo is near.

**Comment by lbalmaceda** [comment]
Hello @sayed19,
By default **Lock** sends the `openid` scope. If you need to override it you'll need to use the method `withAuthenticationParameters()` of the **Lock.Builder** class: i.e.

```java
Map<String, Object> params = new HashMap<>();
        params.put("scope", "openid profile email");
        builder.withAuthenticationParameters(params);

Lock lock = Lock.newBuilder(account, callback)
        .withAuthenticationParameters(params)
        .build(this);
startActivity(lock.newIntent(this));
```

About the old authentication params article I'll send the feedback to the docs team.
Cheers!
