### ISSUE TITLE
NullPointerException onCountryCodeSelected (Nexus 6)

### ISSUE THREAD

**Issue by dmayboroda** [auth0/Lock.Android#377]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.auth0.android.lock.views.PasswordlessFormLayout.onCountryCodeSelected(java.lang.String, java.lang.String)' on a null object reference at com.auth0.android.lock.views.PasswordlessLockView.onCountryCodeSelected(PasswordlessLockView.java:218)

**Comment by lbalmaceda** [comment]
@dmayboroda I guess you're using the `sms` connection but I can't reproduce the exception. Please provide: Repro steps, Android version, Lib version.

Thanks.

**Comment by dmayboroda** [comment]
yes, i use sms connection
android version: 7.0
lib version: 2.1.1
Reproducing steps: open com.auth0.android.lock.CountryCodeActivity and in "Search your county" (EditText searchText) type "uk" and select "Ukraine +380", app crash.

**Comment by lbalmaceda** [comment]
@dmayboroda still can't reproduce it, it may be your device killing old activities when opening the keyboard because the RAM is low. How are you launching Lock? Paste the snippet here or share a sample project if you can. Remember the `CountryCodeActivity` should be opened by Lock itself and not you.

Cheers.

**Comment by dmayboroda** [comment]
I used sample project from original repository. Didn't change anything in code, just launch sample app on my device. I also tried to reproduce this exception on different devices and it works. Thats only on my Nexus 6 :(

**Comment by lbalmaceda** [comment]
@dmayboroda Then I would check on your Nexus 6 device's `Developers Options` that the "Don't keep activities" setting is turned off. Maybe the logcat has something useful too. If you find anything that could help us reproduce and tackle this behavior, feel free to comment and reopen it.

Cheers.
