### ISSUE TITLE
No resource found that matches the given name

### ISSUE THREAD

**Issue by menan** [auth0/Lock.Android#390]
As soon as I add `compile 'com.auth0.android:lock:2.3.0'` to the Gradle file and synced it, I get this following error:
- Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
- Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
- Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
- Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.

My Gradle file looks like this: 
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"
    defaultConfig {
        minSdkVersion 23
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.android.support:support-v4:23.4.0'
    compile 'com.android.support:recyclerview-v7:23.4.0'
    compile 'com.android.support:design:23.4.0'
    compile 'com.mikhaellopez:hfrecyclerview:1.0.0'
    compile 'com.auth0.android:lock:2.3.0'
    compile 'com.koushikdutta.ion:ion:2.+'
    compile 'com.android.support:leanback-v17:23.1.0'
    compile 'com.makeramen:roundedimageview:2.2.1'
    compile 'jp.wasabeef:blurry:2.0.3'
    testCompile 'junit:junit:4.12'
}


```

Here is a screenshot:
<img width="1005" alt="screen shot 2017-01-09 at 3 59 29 pm" src="https://cloud.githubusercontent.com/assets/583642/21783287/aa3e84a4-d684-11e6-9c51-be2ea360c33c.png">

**Comment by lbalmaceda** [comment]
Lock uses support version `25.1.0`. I couldn't reproduce the issue with a small project targeting an older version (24), but that's mostly a support library version error. Try to move at least to major version 25, delete the whole `build` directory and sync the project again. Note that changing the support version will make you change the `compileSdkVersion` to the same major version.

**Comment by menan** [comment]
Okay, Bumping up the SDK version to `25` helped. Thanks @lbalmaceda

**Comment by JanisSharma** [comment]
Already Solved At [Here](https://icetutor.com/question/error-retrieving-parent-for-item-no-resource-found-that-matches-the-given-name-after-upgrading-to-appcompat-v23)
