### ISSUE TITLE
OnBackPressed on Lock activity

### ISSUE THREAD

**Issue by lionelatrecisio** [auth0/Lock.Android#394]
Hello,

First, thank you for your job, your default activity for auth0 is great!

I have a problem with this activity: the "back" button on my devices doesn't work. I can't get back to my previous activity :(

I thank it's not a big deal :)

Thanks,

Lionel

**Comment by lbalmaceda** [comment]
Hi @lionelatrecisio,
By default Lock can't be closed unless the user logs in / sign up successfully. You can change that behavior by calling `closable(true)` in the builder. 

```java
Lock lock = Lock.newBuilder(auth0, callback)
   .closable(true)
   // other config..
   .build(this);
```

That way when the user presses the back button, the `onCanceled` method will be called in your `callback`.

Cheers,
