### ISSUE TITLE
Enterprise Connection (AD) not working

### ISSUE THREAD

**Issue by adrianchia** [auth0/Lock.Android#40]
I was trying enterprise connection (AD) with Lock.Android and it said "There was an error logging in. There was no connection configured for the domain". After debugging I found that the following method  always return null in DomainMatcher.java from https://github.com/auth0/Lock.Android/blob/8bebb7e898c67d7caeda1dc20d06a5b5cd41e8ca/lock/src/main/java/com/auth0/lock/fragment/DatabaseLoginFragment.java#L227
```java
matcher.getConnection () {
  return connection 
}
```

**Comment by hzalaz** [comment]
Hi @adrianchia, I'll take a look at it. Can you send me your app's clientId to `support@auth0.com` so I can see how your app is configured?.
Thanks,

**Comment by adrianchia** [comment]
Sure, I've sent the client ID to support@auth0.com

**Comment by hzalaz** [comment]
@adrianchia just pushed `1.0.1` to Maven Central (It might take a while to be available to download)

**Comment by adrianchia** [comment]
sure, will take a look when it is available on Maven Central. Thanks!
