### ISSUE TITLE
Unable to change default country selected 

### ISSUE THREAD

**Issue by sudhanshunathmishra** [auth0/Lock.Android#404]
Hi, 

I'm on Lock Android version 2.3.0. I have added some strings in my default strings.xml to override some Lock strings, specifically the default country code. While I am able to override successfully for other strings, I am not able to do so for the default country code. 

<img width="678" alt="screen shot 2017-03-11 at 1 30 48 pm" src="https://cloud.githubusercontent.com/assets/10003061/23825816/0c1c9972-065f-11e7-8025-adeb1b256e70.png">

I have initialized my auth0 object as follows 

<img width="462" alt="screen shot 2017-03-11 at 1 33 10 pm" src="https://cloud.githubusercontent.com/assets/10003061/23825826/50cb5748-065f-11e7-8407-5748d2a0c03d.png">

**Comment by lbalmaceda** [comment]
Hi @sudhanshunathmishra,
There's no way to change it within Lock. The default country is chosen by [checking the device's locale](https://github.com/auth0/Lock.Android/blob/master/lib/src/main/java/com/auth0/android/lock/views/CountryCodeSelectorView.java#L101). There's a weird case where the locale's country is null and the fallback will be taken from the `strings.xml` file, as you pointed above. 

Cheers.
