### ISSUE TITLE
NullPointerException in onResume for certain devices

### ISSUE THREAD

**Issue by cvance** [auth0/Lock.Android#415]
Device: Galaxy Note 4 (VZW)
OS: Android 6.0 (API Level 23)
Lock.Android Version: 2.5.0

Crash Log:
```
Unable to resume activity {com.auth0.android.lock.LockActivity}: 
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.auth0.android.lock.views.formLayout.setEnabled(boolean)' on a null object reference 
com.auth0.android.lock.views.ClassicLockView.showProgress (ClassicLockView.java:293)
com.auth0.android.lock.LockActivity.onNewIntent (LockActivity.java:285)
android.app.Instrumentation.callActivityOnNewIntent (Instrumentation.java:1240)
```

I haven't been able to reproduce on any of my devices but this user has encountered it several times since we've added this library.

**Comment by lbalmaceda** [comment]
It seems it's happening after a callback from the browser on the web authentication/passwordless flow, and the cause it's that the device is running out of memory and killing the activity before the actual result arrives. I couldn't reproduce it on this side. This is not a priority for us but I'll leave it open so if anyone has the same issue or knows how to reproduce it we can reevaluate it.

Cheers.

**Comment by viethoang88** [comment]
+1

**Comment by ebudagov** [comment]
I had a similiar issue. In my case, I was able to reproduce it as following:
1. Run application
2. Open android settings
3. Go to application/storage settings and erase all aplication data
4. Run application again

**Comment by lbalmaceda** [comment]
@ebudagov on (1) are you attempting to log in? (e.g. is browser being launched?), also what version of Lock are you using?
