### ISSUE TITLE
Login password bug

### ISSUE THREAD

**Issue by ftitina** [auth0/Lock.Android#418]
Creating a password that ends with ```\``` denies access.

![screenshot_20170622-160928](https://user-images.githubusercontent.com/28537707/27453712-5ef5385a-5765-11e7-86d5-248490875521.png)

Android version - 7.0
Phone Model - Samsung Galaxy S7

**Comment by lbalmaceda** [comment]
@ftitina I can't reproduce it. Please check that the user account you're trying to authenticate with is not blocked. i.e. screenshot:
![image](https://user-images.githubusercontent.com/3900123/27968670-4c967b50-631e-11e7-937f-a66207239abe.png)


Anyway, this is not related in any way to this SDK. If the problem persists you can use https://support.auth0.com and fill in a ticket or ask in the community.
