### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by sebirdman** [auth0/Lock.Android#426]
I recently came across a bug fixed by https://github.com/auth0/Lock.Android/commit/2f9239a38d0c4ca2c8501c9cc30173d1587d210e

seems like it's been a while since a new release, any plans soon for an update?

**Comment by lbalmaceda** [comment]
`2.6.0` already on bintray. Check maven central in a few hours.

**Comment by sebirdman** [comment]
thanks!
