### ISSUE TITLE
Scheme is not being picked up

### ISSUE THREAD

**Issue by ened** [auth0/Lock.Android#433]
- [ ] Code snippet or sample project that reproduces the bug

in AndroidManifest.xml

```
        <activity
            android:name="com.auth0.android.lock.LockActivity"
            android:label="@string/app_name"
            android:launchMode="singleTask"
            android:screenOrientation="portrait"
            android:theme="@style/MyLock.Theme"/>
```

I defined placeholders:
```
        manifestPlaceholders = [auth0Domain: "@string/com_auth0_domain", auth0Scheme: "@string/com_auth0_scheme"]
```
strings.xml:
```
    <string name="com_auth0_domain">company.auth0.com</string>
    <string name="com_auth0_scheme">blulist</string>
```

- [ ] Lock version

2.7.0

- [ ] Android version & Phone Model when appropriate

7.1, Sony XZ performance

- [ ] Versions of Gradle, Android Plugin, Build tools & Android SDK

Gradle plugin 2.3.3, build tools 25, SDK 26.

It seems the scheme is not being picked up. According to the docs, the scheme "blulist" should have been set automatically. 
Instead, I have to set it like this:

```
        lock = Lock.newBuilder(account, callback)
                   .closable(true)
                   .withSignUpFields(fields)
                   .withScheme(getString(R.string.com_auth0_scheme))
                   .build(this);

```

**Comment by lbalmaceda** [comment]
@ened How are you trying to sign in? using what connection?

**Comment by ened** [comment]
Sorry for not mentioning. It's through **google-oauth2**.

**Comment by lbalmaceda** [comment]
Ah yes, you **must** call `.withScheme("yourscheme")` in order to make the library use it. The manifest placeholders are only visible for the gradle files, not for the java code. So there's no way the library can tell which scheme to use at runtime. I'll update the readme as [this](https://github.com/auth0/Lock.Android#android-app-links---custom-scheme) seems outdated. The [quickstart](https://auth0.com/docs/quickstart/native/android/00-login) on the other hand are up to date. 👍 
Thanks for the feedback

**Comment by Paras700** [comment]
how to fix above problem??

**Comment by Paras700** [comment]
> how to fix above problem??

MyLock.theme is not found androidmanifest.xml file how to resolve this problem ???

**Comment by lbalmaceda** [comment]
>MyLock.theme is not found

@Paras700 that is a sample custom theme I created for the sample app included in this repository. If you don't want to customize anything, you can just use the default one as explained in the readme.

```xml
<activity
  android:name="com.auth0.android.lock.LockActivity"
  android:label="@string/app_name"
  android:launchMode="singleTask"
  android:screenOrientation="portrait"
  android:theme="@style/Lock.Theme"/> <--- This line
```
