### ISSUE TITLE
Accessibility label 

### ISSUE THREAD

**Issue by NetPumi2** [auth0/Lock.Android#436]
hello
I have a question. Is there possibility to add accessibility label (or some kind of identification) for buttons in auth0 login? We need it for automation tests...

**Comment by lbalmaceda** [comment]
Like the `contentDescription` attribute? Yes, it can be added. Although many UI components are added programmatically, so it's not just editing the layout xml. This is not a priority for us right now but contributions are always welcome.

**Comment by NetPumi2** [comment]
ok i understand @lbalmaceda 
And i have another question how to set device name? In auth0 admin i select user and his devices and ther is 'okhttp' and i would like to change but i can not find how to send uuid to auth0 for Android and some issue for ios (React native) this topic [https://stackoverflow.com/questions/45959086/auth0-how-to-set-device-name-and-sand-it](stackoverflow).

**Comment by lbalmaceda** [comment]
@NetPumi2 Answered in the react-native-lock repo. ☝️
