### ISSUE TITLE
Rendering problem with social login buttons

### ISSUE THREAD

**Issue by joaom182** [auth0/Lock.Android#44]
The login buttons for social networking are cropped.
Follow the Screenshot:

[http://postimg.org/image/cyur25h13/](http://postimg.org/image/cyur25h13/)

My device is a Galaxy S2 Lite - GT-I9070

**Comment by hzalaz** [comment]
Hi @joaom182,

Thanks for reporting this issue. What is the resolution of that phone? is it mdpi?.

**Comment by joaom182** [comment]
The resolution is 480 x 800
