### ISSUE TITLE
Cannot navigate social login buttons using gamepad on Android TV

### ISSUE THREAD

**Issue by BrianAdams** [auth0/Lock.Android#443]
Lock version: 2.7.0
Android Version: Tested on 7.1 with Nvidia Shield Console

I can use the gamepad to change focus between the Login, Sign Up, and the Email/Password fields.  I cannot set focus by moving the gamepad to the social login buttons so that they can be selected.  I also find that I cannot navigate to the "Don't remember your password?" link.

**Comment by lbalmaceda** [comment]
Definitely, Lock isn't currently enhanced for that kind of navigation. Doesn't the _Shield_ has a mouse pointer that you could use for this screen? Also, how are you performing the authentication, is it using the `WebAuthProvider` class or the embedded `Lock`?

**Comment by BrianAdams** [comment]
I am attempting to use the embedded Lock.  The Shield has a remote control, but it effectively functions as a gamepad's d-pad which look like arrow keys on a keyboard to the OS.  No virtual mouse pointer :-(.

**Comment by lbalmaceda** [comment]
It would be nice to have this fixed but understand we can't commit to an ETA. I'll keep the issue open as a reminder. If you haven't already, try using the `WebAuthProvider` class of the [auth0 library](https://github.com/auth0/Auth0.Android/) and see if that works for you for the time being.

**Comment by lbalmaceda** [comment]
Fixed on https://github.com/auth0/Lock.Android/pull/444. Will try to make a release tomorrow.
