### ISSUE TITLE
Refresh token is null in AuthenticationCallback

### ISSUE THREAD

**Issue by Deathangel908** [auth0/Lock.Android#450]
Lock version : [2.8.0](https://mvnrepository.com/artifact/com.auth0.android/lock/2.8.0).
Could be related to [issue#52](https://github.com/auth0/Lock.Android/issues/52) 

Based on information I've read [here](https://auth0.com/docs/libraries/lock-android/v2/refresh-jwt-tokens) and [here](https://auth0.com/docs/libraries/auth0-android/save-and-refresh-tokens) I cloned this project and:
 -  changed credentials to mine.
 - added `builder.withScope("offline_access openid")`

With all that being said I'm expecting `refreshToken` to be present in AuthenticationCallback after a user has been logged in, but it's null [here](https://github.com/auth0/Lock.Android/blob/master/app/src/main/java/com/auth0/android/lock/app/DemoActivity.java#L288
)
```
 public void onAuthentication(Credentials credentials) {
     showResult("OK > " + credentials.getRefreshToken());
}
```
I've also read If I set `response_type` to `token` instead of default `code` that could solve the issue, unfortunately I can't find the place where I can do it in Auth0Lock.

**Comment by lbalmaceda** [comment]
That `callback` instance you've referenced [here](https://github.com/auth0/Lock.Android/blob/master/app/src/main/java/com/auth0/android/lock/app/DemoActivity.java#L288) is used by "Lock" and not by the "Web Auth" flow, so I'll assume you are using the "Lock" flow. Note that the sample app has a button at the bottom to authenticate using the "Web Auth" flow as well, but that's configured in a different method of the DemoActivity. That said.. Are you sure you've added the `builder.withScope("offline_access openid")` line in [this](https://github.com/auth0/Lock.Android/blob/master/app/src/main/java/com/auth0/android/lock/app/DemoActivity.java#L156) method? If that's true, which type of connection provider are you using?? Is it a social one or is it a database one?

**Comment by Deathangel908** [comment]
I leave checkboxes as they are, and click on `Show Classic` that triggers [showClassicLock](https://github.com/auth0/Lock.Android/blob/master/app/src/main/java/com/auth0/android/lock/app/DemoActivity.java#L156) which I changed:
```
builder
       .withScheme("myscheme")
       .withAudience("https://my.audiance")
       .withScope("offline_access openid profile email");
```
 that has  [this callback](https://github.com/auth0/Lock.Android/blob/master/app/src/main/java/com/auth0/android/lock/app/DemoActivity.java#L288)

I'm using login with password

**Comment by lbalmaceda** [comment]
I can't reproduce it. I cloned this repo, replaced the credentials in the String.xml file with my own. Then added those 3 lines above to the builder configuration and run the sample. When I attempt to log in using a database connection user in classic Lock I get this log output:

```
Request:
D/OkHttp: {"device":"Custom Phone - 5.0.0 - API 21 - 768x1280","password":"******","scope":"offline_access openid profile email","client_id":"***************************","username":"*******","realm":"Username-Password-Authentication","audience":"https://jwks.lbalmaceda.auth0.com","grant_type":"http://auth0.com/oauth/grant-type/password-realm"}

Response:
D/OkHttp: {"access_token":"zzzz.xxxx.yyyy,"refresh_token":"********************","id_token":"zzzz.xxxx.yyyy","scope":"openid profile email delete:photos create:photos update:photos read:photos offline_access","expires_in":86400,"token_type":"Bearer"}
```


Check in your "https://my.audience" API settings (Auth0 Dashboard) that it allows users to obtain a Refresh Token. The next toggle must be turned ON:

![image](https://user-images.githubusercontent.com/3900123/34879429-f5b16086-f78b-11e7-83c9-e4d09f2f00b7.png)

**Comment by Deathangel908** [comment]
@lbalmaceda Thank you, that's it, I need to check that `Allow Offline Access` on the dashboard. Could you please add this to the wiki.

**Comment by lbalmaceda** [comment]
I'm glad it was solved! I'll route this request to the docs team. 
Cheers

**Comment by Mahfuz18** [comment]
If you are still having this problem here is the thing that helped me solve this problem. You will get the refreshToken (not the authcode or access_token) when a mail address registers your app only for the first time. Later it will be null. If you forget to grab the refresh token create a new auth credential from the api console. Then use the client_id and client_secret as usual and grab the refresh token.

code would be like this
---------------------------
$this->tokenInfo = $this->client->fetchAccessTokenWithAuthCode($_GET['code']);
$this->client->setAccessToken($this->tokenInfo);
$refreshToken = $this->client->getRefreshToken();

<best of luck>

**Comment by lbalmaceda** [comment]
Please **do not** include nor use the client_secret as part of a public client such as mobile app. Secrets are meant to be secrets, and there are specific flows designed to be used on these applications that don't need such disclosure. 
The refresh token will be present on the response as long as the `scope` parameter on the log in request included the `openid offline_access` values, and as long as the application is of type "native" with "allow offline access" turned on.

As a reminder, while refresh tokens can be revoked, they **do not** expire and can be used to get a new pair of tokens, so treat them with the same level of secrecy as passwords.

**Comment by DaireJN** [comment]
@lbalmaceda Has the dashboard ui changed? I cannot find the allow offline access toggle
