### ISSUE TITLE
Authentication Callback is showing invalid webpage for the callback url

### ISSUE THREAD

**Issue by mcharamut** [auth0/Lock.Android#46]
I have set the options per the documentation but I am receiving an issue with the callback. 

The webpage at  a0HTQWQV982MouCiNzVXXhoIzpbQc://tenant.auth0.com/authorize................

Could not be found.

 Any ideas what I am missing. In the past when rolling my own providers I had to check for the callback url in order to extract the token. Does the callback url need to be set or any other configuration set. I don't see this as an option.

**Comment by mcharamut** [comment]
When using a webview the method seems to get the callback but it is losing the data somewhere. 

02-24 02:06:08.163  18271-18271/com...... V/com.auth0.identity.WebIdentityProvider﹕ Authenticating with webflow with data a0CLIENTzpbqc://tenant.auth0.com/authorize#access_token=SK''''&id_token=eyJ0e''''''''''''9Q&token_type=Bearer&state=AG'''''''''
02-24 02:06:08.163  18271-18271/com...... D/com.auth0.identity.WebIdentityProvider﹕ Authenticated using web flow
02-24 02:06:08.183  18271-18271/com...... V/com.auth0.lock.LockActivity﹕ Resuming activity with data null
02-24 02:06:08.183  18271-18271/com...... V/com.auth0.identity.WebIdentityProvider﹕ Authenticating with webflow with data null

**Comment by hzalaz** [comment]
Hi @mcharamut,

In your Android Manifest check that you registered the callback URL as an intent filter for `LockActivity`:

```xml
<data android:scheme="a0INSERT_YOUR_APP_CLIENT_ID" android:host="YOUR_ACCOUNT_NAME.auth0.com"/>
```

Also check that the scheme is in lowercase there too, then `LockActivity` will handle the URL and fetch the parameters from there.

**Comment by adrianchia** [comment]
case sensitivity in <data android:scheme > seemed to be the problem, when i placed a0[Client ID copied from Dashboard] shows invalid webpage, when i place a0[Client ID all lowercase] it works.

**Comment by palimad** [comment]
where is this documented? to define callback in manifest for LockActivity?
