### ISSUE TITLE
Provide a way to change white background color in com.auth0.android.lock.LockActivity

### ISSUE THREAD

**Issue by KetanPCoditas** [auth0/Lock.Android#476]
Hi there,
Would you please provide a way to change white background in com.auth0.android.lock.LockActivity screen as we can change HeaderBackground.

<resources>
    <style name="MyTheme" parent="Lock.Theme">
    <item name="Auth0.HeaderLogo">@drawable/com_auth0_lock_header_logo</item>
    <item name="Auth0.HeaderTitle" parent="Lock.Theme.Text.Title">@string/app_name</item>
    <item name="Auth0.HeaderTitleColor">@color/com_auth0_lock_text</item>
    <item name="Auth0.HeaderBackground">@color/com_auth0_lock_header_background</item>
    <item name="Auth0.PrimaryColor">@color/colorPrimary</item>
    <item name="Auth0.DarkPrimaryColor">@color/colorPrimaryDark</item>
</style>

**Comment by lbalmaceda** [comment]
@KetanPCoditas If you still are looking for the answer: IIRC, you can change the "background color" by overriding the color value `com_auth0_lock_form_background` in your own app. This is used here https://github.com/auth0/Lock.Android/blob/master/lib/src/main/res/values/styles.xml#L31.
