### ISSUE TITLE
Lock.Android - Database Connection Sign Up / Login with Scope Issue

### ISSUE THREAD

**Issue by KetanPCoditas** [auth0/Lock.Android#509]
Hi there,

I am using Lock.Android SDK for SignUp/Login with Social and Database Connections options provided by Auth0. With Social Connection, if I set **Scope "openid profile name email nickname offline_access"** in SCOPE_VALUE with builder.withScope(SCOPE_VALUE) with  **Audience: "https://[MY_DOMAIN]"/api/v2/"** then it works perfectly but when I try with Database connection (Email + Password with Auth0 Database - Not using custom database) with same scope and audience, it gives me an error as stated below:

**_{"error":"invalid_scope","error_description":"User is not authorized to the audience for those scopes"}_**

Apart from this, If I get succeeded to sign up using Database connection with whatever scope, will I able to get **AccessToken and RefreshToken in AuthenticationCallback - onAuthentication (Credentials)**?

Thanks,
Ketan

**Comment by lbalmaceda** [comment]
The first one sounds like it should work. Are you using OIDC conformant mode set to true? It's explained [here](https://github.com/auth0/Lock.Android#oidc-conformant-mode).

For the second question, Lock's "sign up" tab does a `create user + log in` (2 requests in total). You will always obtain an access token, but for the refresh token to be present you must include the `offline_access` value in the scope as you're doing in the first question.

**Comment by KetanPCoditas** [comment]
Hi @lbalmaceda , Yes I am setting true for OIDC conformant. If I decode JWT token provided by Auth0, will I able to get email, name fields from token as we pass as an extra information to the builder?

**Comment by KetanPCoditas** [comment]
Hi @lbalmaceda Yes, we have set the scope. With Scope "openid offline_access", I am able. Thanks for the help.

Now I am trying with **Passswordless** options and found that passwordless connection is **deprecated** after **June 2017** as per below listed documentation.

**Lock.Android**: https://auth0.com/docs/libraries/lock-android/v2/passwordless
**Lock.Android Magic Link**: https://auth0.com/docs/libraries/lock-android/v2/passwordless-magic-link
**Auth0**: https://auth0.com/docs/libraries/auth0-android/passwordless
**Passwordless Flow**: https://auth0.com/docs/connections/passwordless/android

What if I try Passwordless API listed over here https://auth0.com/docs/api/authentication#passwordless. Would I able to succeed with integration? 

As I tried with Postman, the API response shows a message that Email sent but I am not receiving any email on passing email address in API? Would you please let me know that is this API is working or not? If working, should I able to integrate it in project as you guys are encouraging developers to use Universal Login features?

Thanks

**Comment by KetanPCoditas** [comment]
Hi @lbalmaceda During integration of Lock.Android along with Auth0.Android, I found that change password does not return an error if user has not registered using **Username-Password-Authentication** connection and enter valid email address in Change Password flow.

I have designed Change Password screen by myself and called resetPassword using AuthenticationAPIClient.
```
AuthenticationAPIClient apiClient = options.getAuthenticationAPIClient();
apiClient.resetPassword(email, connection).start(changePwdCallback);
```
In this screen, initially I am validating entered email is valid or not i.e in the valid format like **abc@def.com** and after then I am passing this email to resetPassword method along with database connection name (which would be Username-Password-Authentication). In this method, If I pass email like afafaf**abc@def.com** which is not valid and not registered using Username-Password-Authentication in Auth0 even though it shows success message in changePwdCallback -> public void onSuccess(Void payload) method.

Would you please let me know that does Auth0 check if the provided email id exists in database or not with mentioned database connection?

**Comment by lbalmaceda** [comment]
You'll never receive an unsuccessful response on that endpoint, and that's on purpose to prevent email enumeration. You can read more about it on this [community response](https://community.auth0.com/t/validate-if-email-address-exists-in-locks-forgot-password-screen/8335/2).
