### ISSUE TITLE
Refresh token null

### ISSUE THREAD

**Issue by joaom182** [auth0/Lock.Android#52]
Hello,

The property `refreshToken` is coming `null` from `token` on object received in authentication callback.

Without refreshToken can not revalidate the authentication if it is expired, right?

**Comment by hzalaz** [comment]
We have an issue #53 with the default scope that should retrieve `refresh_token` when authenticating. To bypass this issue do the following when initialising `Lock`:

```java
Map<String, Object> params = ParameterBuilder.newBuilder().asDictionary();
lock = new LockBuilder()
        .loadFromApplication(this)
        .authenticationParameters(params)
//Your Lock config options
        .build();
```

**Comment by hzalaz** [comment]
The `refresh_token` is returned when the scope parameter contains `offline_access` string, e.g.: `openid offline_access` which should be the default. Also when sending `offline_access` in the scope, you must to send an additional authentication parameter called `device` with the device's name (The default now is to use `Build.Model` constant.

But `ParameterBuilder.newBuilder()` by default sets the scope to `openid offline_access` and the device to the value of `Build.Model` so unless you have a special scope setting, the previous snippet will help you

**Comment by mauriciocoelho** [comment]
my settings to initialize the lock:

```java
Map<String, Object> params = ParameterBuilder.newBuilder().asDictionary();
        lock = new LockBuilder()
                .loadFromApplication(this)
                .authenticationParameters(params)
                .closable(true)
                .build();
```


my parameter settings being sent are:
```
{device=Nexus 4, scope=openid offline_access}
```

My return is:
![capturar](https://cloud.githubusercontent.com/assets/5712300/6849369/93b88f68-d3b1-11e4-9631-f7d1e94f96a9.PNG)

**Comment by hzalaz** [comment]
@mauriciocoelho that's strange. I initialise Lock like this:
```java
        Map<String, Object> params = ParameterBuilder.newBuilder().asDictionary();
        lock = new LockBuilder()
                .loadFromApplication(this)
                .closable(true)
                .authenticationParameters(params)
                .build();
        lock.setProvider(Strategies.Facebook.getName(), new FacebookIdentityProvider());
        lock.setProvider(Strategies.GooglePlus.getName(), new GooglePlusIdentityProvider(this));
```

and I get the `refresh_token` (Value is Edited for security purposes):

![screenshot 2015-03-26 12 36 22](https://cloud.githubusercontent.com/assets/895992/6849938/be7b2f6e-d3b4-11e4-9d6a-a340ef5c272a.png)

@mauriciocoelho, @joaom182  what version of Lock are you using?

**Comment by mauriciocoelho** [comment]
this are the versions:
```java
'com.auth0.android:lock:1.1.+'
'com.auth0.android:lock-facebook:1.1.+'
'com.auth0.android:lock-googleplus:1.1.+'
```

![capturar](https://cloud.githubusercontent.com/assets/5712300/6852422/4a180782-d3c3-11e4-99ce-892ef190c419.PNG)

**Comment by hzalaz** [comment]
@mauriciocoelho try using the latest version 1.3.0

**Comment by mauriciocoelho** [comment]
@hzalaz updated to latest version, also tried with different providers and the problem persists :(

![version](https://cloud.githubusercontent.com/assets/5712300/6854462/40539a9c-d3d0-11e4-88d8-77b5c4b65324.PNG)

![tokennull](https://cloud.githubusercontent.com/assets/5712300/6854464/445ad0ec-d3d0-11e4-89d9-6fc20d7878dd.PNG)

**Comment by hzalaz** [comment]
@mauriciocoelho I tried also with our [sample](https://auth0.com/docs/quickstart/native-mobile/android/no-api) and its returning a non-null `refresh_token`. I've only changed the `onCreate` method of `SampleApplication` to set the default parameters:

```java
    @Override
    public void onCreate() {
        super.onCreate();
        lock = new LockBuilder()
                .loadFromApplication(this)
                .authenticationParameters(ParameterBuilder.newBuilder().asDictionary())
                .build();
        lock.setProvider(Strategies.Facebook.getName(), new FacebookIdentityProvider());
        // More stuff not related to Lock
    }
```
Can you check against our [sample](https://auth0.com/docs/quickstart/native-mobile/android/no-api) and see what's different in your app?

**Comment by mauriciocoelho** [comment]
I downloaded your sample project, I imported the android studio, I set my auth0 data and I'm still getting null.

![sampleapp](https://cloud.githubusercontent.com/assets/5712300/6857041/bef66016-d3e2-11e4-9bd6-031b76a5d607.PNG)

**Comment by hzalaz** [comment]
@mauriciocoelho can you go to [http://chat.auth0.com/](http://chat.auth0.com/) and ask this question there?.

**Comment by hzalaz** [comment]
This is also related to #54 when using social authentication without native integration

**Comment by joaom182** [comment]
Thanks Hernan! ;)

**Comment by hzalaz** [comment]
@joaom182 @mauriciocoelho, version `1.3.1` is published in maven central. Let me know if it works.

**Comment by mauriciocoelho** [comment]
worked! thank @hzalaz
