### ISSUE TITLE
Facebook Policy Warning for App

### ISSUE THREAD

**Issue by ketanPRO** [auth0/Lock.Android#524]
This is new Facebook brand guidelines requirement from facebook. It's not a bug, so I am not following regular steps.

We have got warning mail from Facebook that we need to update Facebook login button as per their brand guidelines. Below is the mail we received from Facebook. It seems Lock UI for swift & android platform needs to update to accommodate this new change. can you update sdk asap ?

Hi,

In working to create a great Platform experience for everyone, we ask developers to ensure the apps they build comply with our Platform Policies. Your app doesn't comply with the following:

Platform Policy 8.3: Use a clearly branded "Login with Facebook" button and follow the Facebook Brand Guidelines: https://www.facebookbrand.com/.

Your iOS Login button doesn't properly reference Facebook. To fix this issue, you should always use our official iOS SDK for Login.

Here are some useful resources to follow:
• Quickstart guide for implementing Facebook Login for iOS: https://developers.facebook.com/docs/facebook-login/ios
• Submission guidelines: https://developers.facebook.com/docs/apps/review/submission-guidelines
• Information on Login best practices: https://developers.facebook.com/docs/facebook-login/best-practices#buttondesign

Platform Policy 8.3: Use a clearly branded "Login with Facebook" button and follow the Facebook Brand Guidelines: https://www.facebookbrand.com/.

Your Android Login button doesn't properly reference Facebook. To fix this issue, you should always use our official Android SDK for Login.

Here are some useful resources to follow:
• Quickstart guide for implementing Facebook Login for Android: https://developers.facebook.com/docs/facebook-login/android
• Submission guidelines: https://developers.facebook.com/docs/apps/review/submission-guidelines
• Information on Login best practices: https://developers.facebook.com/docs/facebook-login/best-practices#buttondesign

You can access the full list of our Platform Policies here: https://developers.facebook.com/policy/.

**Comment by lbalmaceda** [comment]
Thanks! I pushed a PR solving this.

**Comment by shaikhmohsink** [comment]
Eagerly waiting for an update on the android SDK as well, as the above mentioned issue form ketanPRO applies to our android apps as well. Currently the released version that has the issue is 2.12.1, expecting an updated release. Thanks!

Attached is the screenshot from an android app, here is how the facebook icon looks like

![Screenshot_20190417-132926](https://user-images.githubusercontent.com/7204180/56293592-f525a200-6146-11e9-9cd8-46cf02a04158.jpg)
