### ISSUE TITLE
Can we change auth0.com on account selection screen with google social sign in?

### ISSUE THREAD

**Issue by KetanPCoditas** [auth0/Lock.Android#533]
Hi there,

When we tap on the Google button in this screen 
![SocialSignIn_Auth0](https://user-images.githubusercontent.com/39261072/58308711-f8840b80-7e1f-11e9-9fba-af7ce47eec53.png), it will open this screen 
![SocialSignIn_AccountSelect_Auth0](https://user-images.githubusercontent.com/39261072/58308730-046fcd80-7e20-11e9-8327-d15633f58a6f.png).

Can we change the **auth0.com** (Written in blue) on account selection screen with google social sign in? Please see in the attached image.

Thanks, 
Ketan

**Comment by lbalmaceda** [comment]
@KetanPCoditas It looks like to get what you want you'll need to make use of [custom domains](https://auth0.com/docs/custom-domains). But this isn't an SDK issue so I encourage you to contact support directly at https://support.auth0.com so they can better assist you.
