### ISSUE TITLE
Typo on password reset toast, COULDNT't

### ISSUE THREAD

**Issue by michaelbyrd123** [auth0/Lock.Android#540]
### Description

Typo on toast when logging in if you go to reset password and send to the same email past maximum attempts you receive a misspelled toast error.

### Environment

Version of the Lock.Android used: 2.14.1

### Reproduction

Any device, go to reset password.  Submit an email address and keep returning to reset password and sending reset email until you get an error.  The error shows the misspelled message.

**Comment by lbalmaceda** [comment]
@michaelbyrd123 the string resource seems to be correctly spelled, escaping the `'` char. Can you please check if you are overriding it on your app?

**Comment by lbalmaceda** [comment]
Never mind, this was already fixed by the time I checked this. Thanks for reporting it 👍
