### ISSUE TITLE
Cannot get rid of Login with Google

### ISSUE THREAD

**Issue by geertberkers** [auth0/Lock.Android#546]
How can I get rid of this stupid Google Login button?

![WhatsApp Image 2019-08-14 at 21 47 15](https://user-images.githubusercontent.com/8653723/63051277-36537600-bedd-11e9-81a8-51b38b38cf88.jpeg)

My code:

    private val clientId by lazy {
        getString(R.string.com_auth0_client_id)
    }

    private val domain by lazy {
        getString(R.string.com_auth0_domain)
    }

    private val auth0 by lazy {
        Auth0(clientId, domain).apply {
            isOIDCConformant = true
        }
    }

    private val apiClient by lazy {
        AuthenticationAPIClient(auth0)
    }

    private val manager by lazy {
        CredentialsManager(apiClient, SharedPreferencesStorage(this))
    }

    private val authentication by lazy {
        AuthenticationAPIClient(auth0)
    }

    private val lock by lazy {
        Lock.newBuilder(auth0, authenticationCallback)
            .allowShowPassword(false)
            .withScope("openid profile offline_access password")
            .withAudience("https://medication-reference.zorgkluis.nl")
            .setDefaultDatabaseConnection("Username-Password-Authentication")
            .build(this)
    }

And I use `startActivity(lock.newIntent(this))` in the onCreate()

**Comment by lbalmaceda** [comment]
@geertberkers you have a few options. 

You can disable the connection for all your applications in auth0:

![image](https://user-images.githubusercontent.com/3900123/64979569-5dabb300-d88e-11e9-970d-e188e8aec134.png)

Or you can open your application's settings, click the connections tab and disable it from there:
![image](https://user-images.githubusercontent.com/3900123/64979632-787e2780-d88e-11e9-954f-c4394be64bc0.png)

Or you can also whitelist the connections that this SDK will use from the code, using [this method](https://github.com/auth0/Lock.Android/blob/master/lib/src/main/java/com/auth0/android/lock/Lock.java#L308) before building the instance.
