### ISSUE TITLE
Unable to login for UI tests because EditText view IDs not unique

### ISSUE THREAD

**Issue by CarsonRedeye** [auth0/Lock.Android#548]
### Description

Android pre-launch report allows us to set a username and password for Google's app crawler to login and test the app automatically. However, it requires the resource id of the username edittext, the password edittext and the login button. LockActivity does not specify unique resource ids for these items so Pre-launch report can't log in.

### Prerequisites

- [x] I have checked the [README](https://github.com/auth0/Lock.Android/blob/master/README.md) for this library.

- [x] I have checked the [Auth0 Community](https://community.auth0.com/) for related posts.

- [x] I have checked for related or duplicate [Issues](https://github.com/auth0/Lock.Android/issues) and [PRs](https://github.com/auth0/Lock.Android/pulls).

- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).

- [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

- [x] I am reporting this to the correct repository (consider [Auth0.Android](https://github.com/auth0/Auth0.Android) and [Lock](https://github.com/auth0/lock)).

### Environment

Please provide the following:

- Version of the Lock.Android used: 2.15.0
- Version of the Android used: 28

### Reproduction

1. Use layout inspector on LockActivity. 
2. See that username and password edittexts ids are the same, and login button has no id.

**Comment by CarsonRedeye** [comment]
This is still a problem, for basically every customer. They might not realise it but they are not able to take advantage of googles free app crawler

**Comment by lbalmaceda** [comment]
@CarsonRedeye I'm checking the layout inspector on the LockActivity (classic lock) and seeing the following:

Fields:
- **Username/Email** input has ID `com_auth0_lock_input_username_email`
- **Username** input has ID `com_auth0_lock_input_username` (when "requires username" is true, this one is shown and the one above expects an email value)
- **Password** input has ID `com_auth0_lock_input_password`

Buttons:
- **Labeled button** has ID `com_auth0_lock_labeled`
- **Icon button** has ID `com_auth0_lock_icon`
There's no main ID for the whole button layout, this one is indeed lacking. But I guess clicking one of the children mentioned above could do just fine.

![image](https://user-images.githubusercontent.com/3900123/71479709-6d635d80-27d4-11ea-8fe9-0d29da711dda.png)


Please see if that's enough for the test tool requirements.

**Comment by CarsonRedeye** [comment]
Hi this does not work. The view you refer to, `com_auth0_lock_input_username_email`, is not an `EditText` view (it extends `LinearLayout`) and therefore cannot be used as the input field by google play console. The edit text for both email and password is called `com_auth0_lock_input`. See attached screenshot": 
![Screen Shot 2020-01-28 at 2 45 22 pm](https://user-images.githubusercontent.com/44560503/73234113-ee9b7f00-41dc-11ea-96ed-90836e6924bd.png)

**Comment by lbalmaceda** [comment]
Correct, they extend `LinearLayout` because they are a custom view; still, they have a [setText()](https://github.com/auth0/Lock.Android/blob/master/lib/src/main/java/com/auth0/android/lock/views/ValidatedInputView.java#L423) method that relays that to the inner `EditText` child. I'm guessing here as I've never used this testing feature before, but wouldn't you be able to configure that console and to call `setText()` on this custom view element? Just like you would on a `EditText`.

Adding an ID to that `EditText` child element will not make it any different, as all instances will have the "same" ID. What matters to us is the ID of the outer element, which is the one I pointed out on my previous comment. That is the ID we use to locate and position the view element in the layout. We're not changing the custom view implementation.

**Comment by CarsonRedeye** [comment]
That may be the case, but I can confirm that google pre-launch report does not work with the current names. I've tested it. However if I change the `EditText` names, and use them, it does work. There is no configuration in the console other than setting the name of the `EditText` unfortunately.

**Comment by CarsonRedeye** [comment]
This configuration does work, where I have changed the name of the password edit text:
![Screen Shot 2020-01-29 at 10 57 31 am](https://user-images.githubusercontent.com/44560503/73316162-3f1ae700-4286-11ea-9643-3ec861fd91df.png)

**Comment by lbalmaceda** [comment]
🎉 If it works I guess it's being named internally/automatically. But is weird because we don't define any id with the name `com_auth0_lock_input_password_edit_text`.
