### ISSUE TITLE
How can i customize error messages of lock?

### ISSUE THREAD

**Issue by ShaktiSubhraPSwain** [auth0/Lock.Android#551]
I tried with editing strings file but that does not work. Not getting from where messages are coming.

**Comment by lbalmaceda** [comment]
@ShaktiSubhraPSwain you need to add a new string resource entry **in your application** using the same name of the resource that lock is using for that specific error scenario. 

e.g. if you want to customize the error displayed when you try to sign up with an existing username or email address:

https://github.com/auth0/Lock.Android/blob/master/lib/src/main/java/com/auth0/android/lock/utils/CustomField.java#L69

you need to **add** a new resource to your application using as key `com_auth0_lock_db_signup_user_already_exists_error_message`.
