### ISSUE TITLE
Question: Login and Sign Up Provider Analytics

### ISSUE THREAD

**Issue by morganlutz** [auth0/Lock.Android#554]
### Description

How can we retrieve the login and/or sign up provider information? i.e. when a user signs up with facebook, we need to send a sign up analytics event with the value "facebook". I don't see an easy way to do this, but I could be missing something. Thanks in advance!

**Comment by lbalmaceda** [comment]
The provider chosen by the user is not included in the authentication response, so no, from the client there's no way to do that. I guess this is something you can code in a [Rule](https://auth0.com/docs/rules/) and make a request from there after every user sign up / auth.

**Comment by morganlutz** [comment]
We also like to track these actions client side because it is useful when investigating crashes. For example, many if not all crash tracking libs will list all analytics and breadcrumb events that lead up to a crash to better help developers repro the issue. Is there any way we can expose user actions to 3rd party consumers? A simple, optional callback would work well for analytics and breadcrumb tracking. I would be happy to put up a PR based on whatever requirements you have.

**Comment by lbalmaceda** [comment]
Leaving errors a side for a moment and thinking out loud, for successful logins that result in an ID token you could decode that token and get the `sub` claim which would have a format similar to the next: `{identity_provider}|{user_id}`. Extracting that first value you'd now the connection used. But as mentioned in my first comment, that's something you're already provided on a Rule and is probably better to do it there than in the client.

But tracking user events.. I don't think that's something we really want to open up to, even when optional. We're not huge fans of analytics. 

I can't think of any other way for you to resolve this error scenario you mentioned. Have you been running into many exceptions lately? And if so, maybe you want to share that instead so we can help you fix them? 
Cheers

**Comment by morganlutz** [comment]
Thanks for the info! We will go with a forked version until we can write our own UI.
