### ISSUE TITLE
Submit button covered by bottom nav on Android

### ISSUE THREAD

**Issue by tlhinman** [auth0/Lock.Android#555]
We're using Lock 11.17.2 and hitting the following issue in Chrome on a Pixel 2 (includes screenshot): https://community.auth0.com/t/submit-button-covered-by-bottom-nav-on-android/33640

Thanks for your assistance!

**Comment by lbalmaceda** [comment]
@tlhinman this belongs to [auth0/lock](https://github.com/auth0/lock/). Please create the issue there.
