### ISSUE TITLE
Sign in with Apple Branding

### ISSUE THREAD

**Issue by horsejockey** [auth0/Lock.Android#565]
### Description

The "Sign in with Apple" button on Android is missing the apple logo and branding. 

### Reproduction

Enable sign in with apple for your native application and you will see the button appear in Android lock view without the proper branding.

### Environment

Tested on 2.17.1 and 2.18.0

Android 9

![IMG_4611](https://user-images.githubusercontent.com/2307109/79505614-e12ead80-7ff1-11ea-9c96-50c519bbbbdd.jpg)

**Comment by lbalmaceda** [comment]
@horsejockey 👋 Thanks for creating this one. It looks like the fallback design for when there's no particular design for the connection. 

I've got a question though, does SIWA work from an Android device? I assumed it didn't, thus why never added any branding to it.

**Comment by morganlutz** [comment]
@lbalmaceda SIWA should work from any device that has a web browser. See [Use Sign in with Apple on other platforms](https://support.apple.com/en-us/HT210318).

**Comment by lbalmaceda** [comment]
Thank you for that link @morganlutz ,

I've added this to our backlog. That means its priority will get decided during the next team call. 

In the meantime, while this is not a global solution, you could define your own style for that connection following the steps detailed [here](https://auth0.com/docs/libraries/lock-android/v2/custom-theming#custom-oauth-connection-buttons).

**Comment by horsejockey** [comment]
@lbalmaceda Sorry, I missed your question but thanks for posting a work around!
