### ISSUE TITLE
Login Chrome Tab 404 Android 10

### ISSUE THREAD

**Issue by adelpuva** [auth0/Lock.Android#566]
Device: Android Pixel 3a, Android 10

Into manifest:
```xml
 <activity
        android:name="com.auth0.android.lock.LockActivity"
        android:label="@string/app_name"
        android:launchMode="singleTask"
        android:screenOrientation="portrait"
        android:theme="@style/Lock.Theme"
       tools:ignore="LockedOrientationActivity"/>
```

When launch activity:
```kotlin
   lock = Lock.newBuilder(auth0, lockCallback)
        .withAudience("https://${context.getString(R.string.auth0_domain_url)}/userinfo")
         .closable(true)
         .withScope("openid profile email")
         .build(context)
     startActivity(context, lock.newIntent(context), null)
```
And choose "**Sign in with Google**"
 
Chrome tab show 404 error:
![1](https://user-images.githubusercontent.com/1243844/80232320-01dfae80-8655-11ea-9f57-d6559164aac9.png)

If select "Open in Chrome" from menu and I select my App (no chrome) login works.

Can i Fix it?

Thank you

**Comment by byavallone** [comment]
I also reproduced this issue with a Huawei P30. My settings are just like yours.

**Comment by lbalmaceda** [comment]
Do you face this issue after successfully logging into Google, when the redirection is supposed to take you to your app?

**Comment by adelpuva** [comment]
Maybe... Infact, if I choose to open the 404 page with MyApp (not chrome as suggest bottom menu when choose "**Open In Chrome**") I log in with success and back to my activity that launched Lock login.

Here some relevant log (I hope):
```log
I/ActivityTaskManager: START u0 {flg=0x10000000 cmp=mypackage/com.auth0.android.lock.LockActivity (has extras)} from uid 10134
V/LockActivity: Looking for a provider to use /authorize with the connection google-oauth2
D/LockActivity: Couldn't find an specific provider, using the default: WebAuthProvider
V/CallbackHelper: The Callback URI is: https://mysite.eu.auth0.com/android/mypackage/callback
V/OAuthManager: Using PKCE authentication flow
I/ActivityTaskManager: START u0 {flg=0x4000000 cmp=mypackage/com.auth0.android.provider.AuthenticationActivity (has extras)} from uid 10134
D/CustomTabsController: CustomTabs Service connected
D/CustomTabsController: Launching URI. Custom Tabs available: true
I/ActivityTaskManager: START u0 {act=android.intent.action.VIEW dat=https://mysite.eu.auth0.com/... pkg=com.android.chrome cmp=com.android.chrome/com.google.android.apps.chrome.IntentDispatcher (has extras)} from uid 10134
I/ActivityTaskManager: START u0 {act=android.intent.action.VIEW dat=https://mysite.eu.auth0.com/... flg=0x800000 pkg=com.android.chrome cmp=com.android.chrome/org.chromium.chrome.browser.customtabs.CustomTabActivity (has extras)} from uid 10113
Logging event: origin=auto,name=user_engagement(_e),params=Bundle[{ga_event_origin(_o)=auto, engagement_time_msec(_et)=5190, ga_screen_class(_sc)=LockActivity, ga_screen_id(_si)=-9105951929193680511}]
V/FA-SVC: Logging event: origin=auto,name=screen_view(_vs),params=Bundle[{ga_event_origin(_o)=auto, ga_previous_class(_pc)=LockActivity, ga_previous_id(_pi)=-9105951929193680511, ga_screen_class(_sc)=AuthenticationActivity, ga_screen_id(_si)=-9105951929193680510}]
W/ProcessService9: type=1400 audit(0.0:552): avc: denied { getattr } for path="/data/data/com.android.chrome" dev="vdc" ino=123185 scontext=u:r:isolated_app:s0:c58,c291,c512,c768 tcontext=u:object_r:app_data_file:s0:c113,c256,c512,c768 tclass=dir permissive=0
```

**Comment by lbalmaceda** [comment]
@adelpuva Thanks. It seems to be happening at the redirect stage, after successfully logging in with Google.

The very first time you try to log in the browser doesn't have any cookie and will ask you to fill your google email and google password. In that scenario, I assume you are being successfully redirected back to your app. ✅ 
But the consecutive calls will not ask you for credentials because the browser remembers your session with google and performs an "auto-login". That redirects back to the app is automatic and gets blocked by the browser app because there's no explicit user action over the page contents that triggered it. 🚫 Basically, the browser thinks you are a robot 🤖. Please check if you're in this situation by retrying the authentication, first manually logging out from google.

**Comment by adelpuva** [comment]
You are right!
First I log out from Chrome, and then login works well!
Obviously, at second time... the same problem again!

How can I fix? 
Thank you

**Comment by lbalmaceda** [comment]
@adelpuva You need to provide a way for those users that are "already logged in" in that external identity provider, to "click" somewhere on the page to complete the authentication. By complete, I mean getting redirected back to your app.

Fortunately, there's an easy way to do that today which I hope fixes your issue. Open your Auth0 dashboard. Go to the Tenant settings (top right of the page) and select the tab for the Advanced settings. Find this SSO setting and turn it off as on the screenshot below. Remember to SAVE the changes.

![image](https://user-images.githubusercontent.com/3900123/80256302-eaa0c100-8654-11ea-9fee-a2ab62c04150.png)

What that will do is, the next time you are in this "already logged in" scenario, it will tell you "last time you were logged in with.... click here to use that account". That button click is the action you're looking for.

**Comment by adelpuva** [comment]
I don't see "**Enable seamless SSO**" inside _Log in Session managment_, bu only this:

<img width="874" alt="Screenshot 2020-04-24 at 23 18 32" src="https://user-images.githubusercontent.com/1243844/80257799-03739b80-8682-11ea-9777-8c8bc61d8aa5.png">

**Comment by lbalmaceda** [comment]
@adelpuva I wasn't aware of that. Checking the docs, that seems to be an option for legacy tenants, which tenants created this year don't have. Sorry about that.

There are two options available then: 
- Either code and host a page you can put as the callback URL, that will show a button to "complete the authentication" and when clicked will take you back to the app, sending all the arguments received from the server (tokens!) or...
- Depending on the provider you've chosen to authenticate with, send the _prompt_ parameter to force the external IdP to ask for credentials or to select an account. This really depends on each IdP so there's no generic solution, as most support different values. You'll have to search for "{name of the identity provider} prompt values".

In the case of Google, I'd try the following values: `prompt=login` and `prompt=select_account` as detailed in their [docs](https://developers.google.com/identity/protocols/oauth2/openid-connect#authenticationuriparameters). You'll have to use this [method](https://github.com/auth0/Lock.Android/blob/master/lib/src/main/java/com/auth0/android/lock/Lock.java#L297) to set them on the Lock builder.

**Comment by adelpuva** [comment]
Using `prompt=select_account` works!
Thank you!

**Comment by lbalmaceda** [comment]
I'm glad it worked. If you run into any SDK issue don't hesitate to open a new one.
