### ISSUE TITLE
EditTexts are not showing up

### ISSUE THREAD

**Issue by BesatZardoshtCarfax** [auth0/Lock.Android#567]
### Description

I have completed all the steps from the documentation and I can see the lock activity but there is no input field in this activity.

<img width="322" alt="Screen Shot 2020-04-28 at 5 27 45 AM" src="https://user-images.githubusercontent.com/52752909/80471517-83fbfb80-8911-11ea-8ef2-37d0f9d7ac67.png">

**Comment by Edward-Kaschula** [comment]
I see this in all my environments including production. Downloaded our app from store now to check and there is no username and password fields showing on Login Screen and no fields on the sign up screen either.

**Comment by Edward-Kaschula** [comment]
I found that if I change my build.gradle to 
implementation 'com.google.android.material:material:1.0.0'
rather than the newer 
implementation 'com.google.android.material:material:1.1.0'
everything works again

**Comment by BesatZardoshtCarfax** [comment]
> I found that if I change my build.gradle to
> implementation 'com.google.android.material:material:1.0.0'
> rather than the newer
> implementation 'com.google.android.material:material:1.1.0'
> everything works again

For me it's already 1.1.0

**Comment by Edward-Kaschula** [comment]
Yes so change it to 1.0.0 that will fix the problem

**Comment by BesatZardoshtCarfax** [comment]
Thanks.. That did fix the issue! But I need the latest material library! I still think this issue is valid since the library is not compatible with the latest material library

**Comment by Edward-Kaschula** [comment]
Yes, this needs to be fixed so that we can use the correct Google libraries. The solution here is only a temporary work around. @Auth0 please fix this.

**Comment by ivabra** [comment]
Got the same problem and I've done too far for rolling back to the previous version of material components library, so I put some efforts to get it work for me.

**Comment by BesatZardoshtCarfax** [comment]
Amazing.. Hopefully the review would be quick..

**Comment by lbalmaceda** [comment]
👋 Thanks for creating this. It's indeed an error that needs to be addressed. 

However, I'm trying to reproduce the issue and can't. I've created a new android project from scratch, using Android X and Lock 2.18.0. After following the steps on the Lock's readme, I obtain a simple app that's only meant to launch the LockActivity in order to test the tabs component. Adding the dependency `'com.google.android.material:material:1.1.0'` and even changing it to 1.0.0 doesn't trigger this error. Can someone share more details or even a simple repro project I could try the PR on? For example, AndroidX or AppCompat libraries, dependencies included, API version targetted, etc.

**Comment by Edward-Kaschula** [comment]
@lbalmaceda you can use this sample project that I have created that shows this happening. Put in an auth0 domain and client id in the Strings.xml to make it work after cloning and building. 
When running this project the expected result is that the login screen will not have the username and password controls showing. 

If you change implementation 'com.google.android.material:material:1.1.0' in the module level build.gradle to implementation 'com.google.android.material:material:1.0.0' and run the project, the controls will then show.

https://github.com/Edward-Kaschula/SampleAuth0.git

**Comment by lbalmaceda** [comment]
Thanks for sharing that. I found the reason why I couldn't repro this. My emulator was running Android 25. I've tried on 28 and 30 and the issue is now visible in both.
I'll check @ivabra PR locally and will help with a release soon. 🙌

**Comment by fairlyNguyen** [comment]
Now it happen when I using latest material version, v1.4.0. Any idea can help?
