### ISSUE TITLE
Provide integration with AndroidX BiometricPrompt

### ISSUE THREAD

**Issue by rubixhacker** [auth0/Lock.Android#569]
Please provide integration with BiometricPrompt to support devices with Fingerprint, Face Scanning and additional biometric authentication mechanisms

https://developer.android.com/reference/androidx/biometric/BiometricPrompt

**Comment by lbalmaceda** [comment]
@rubixhacker as mentioned on the issue above, this is something I was expecting the OS to provide OOTB when it's configured and available on the device. But as I read [here](https://developer.android.com/reference/android/app/KeyguardManager#createConfirmDeviceCredentialIntent(java.lang.CharSequence,%20java.lang.CharSequence)), the method got deprecated and replaced by the one you referenced for APIs 29 and above.

I'll add this feature request to our team's backlog and proceed to close the issue. But the conversation remains open.
