### ISSUE TITLE
Show error message returned from a rule

### ISSUE THREAD

**Issue by hzalaz** [auth0/Lock.Android#57]
When trying to authenticate a user and a Rule returns an error like:
```json
{
  "error": "unauthorized",
  "error_description": "You need to count to 10 before you can access this application."
}
```
Show the content of `error_description` to the user.

**Comment by ritdaw** [comment]
Any update on this one? Really need this before going live with our app and web backend.

**Comment by hzalaz** [comment]
@ritdaw I think we can have it tomorrow EOD.
What we are planning to do is show the content of `error_description` when authentication fails an the error code is `unauthorized`. The only issue I see with this is i18n because we'll show the message directly to the user so that should be handled in the rule itself.

What are your thoughts on this?

**Comment by ritdaw** [comment]
Great. Content of error message displayed in a dialog would be fine.

**Comment by hzalaz** [comment]
:+1: we'll add this tomorrow.

**Comment by ritdaw** [comment]
Excellent.
