### ISSUE TITLE
Login Chrome Tab 404 With Facebook

### ISSUE THREAD

**Issue by adelpuva** [auth0/Lock.Android#572]
I've resolved this problem with this issue #566 adding this to lock builder:
```kotlin
.withAuthenticationParameters(mapOf("prompt" to "select_account"))
```

But the same problem happens with Facebook Login. I'v searched the right parameters, but no works?
```kotlin
            .withAuthenticationParameters(
                mapOf(
                    "prompt" to "select_account",
                    "auth_type" to "reauthenticate"
                )
            )
```

Any idea? @lbalmaceda

**Comment by lbalmaceda** [comment]
For Facebook, they don't seem to accept a `prompt` value, or at least I couldn't find a doc for that. I did find this however https://developers.facebook.com/docs/facebook-login/reauthentication/. As mentioned on the linked issue, this really depends on each identity provider and is external to Auth0 or this SDK. 

I'd try with that `auth_type=reauthenticate`. This is also posted on a SO question dated from 2018 https://stackoverflow.com/a/52462041. But I haven't tested it. 

Cheers

**Comment by adelpuva** [comment]
I try to use native login with facebok., i follow this tutorial: 
https://github.com/auth0-samples/auth0-android-native-social-sample

But `loginWithNativeSocialToken` does not exists!, I switch to `loginWithOAuthAccessToken` but the response is `An error occurred when trying to authenticate with the server`

Thank you

**Comment by adelpuva** [comment]
I switch to native login... I use this code with success:
```kotlin
 auth0Client
     .loginWithNativeSocialToken(token, FACEBOOK_SUBJECT_TOKEN_TYPE)
     .setScope("openid profile email")
     .addAuthenticationParameters(mapOf("user_profile" to profile))
```
Using Google, what is the right `tokenType`? And  `user_profle`?

**Comment by lbalmaceda** [comment]
@adelpuva "native authentication" is only available for Sign-In with Apple and Facebook connections for now, with the later being on _beta_. You can check the supported connections here https://auth0.com/docs/connections/identity-providers-social.
