### ISSUE TITLE
Custom Fields at Signup not adding more than 2 fields

### ISSUE THREAD

**Issue by amankumar367** [auth0/Lock.Android#574]
### Description

> When I was trying to add more than 2 custom signup fields, the other 2 fields are also gone and it's becomes like default one.

### Reproduction

> Detail the steps taken to reproduce this error, what was expected, and whether this issue can be reproduced consistently or if it is intermittent.
>
> - Code sample to reproduce the issue

```
private fun openLockSDKScreen(screen: Int) {
        val lockBuilder = getLockBuilder()

        when(screen) {
            InitialScreen.LOG_IN -> lockBuilder.initialScreen(InitialScreen.LOG_IN)
            InitialScreen.SIGN_UP -> lockBuilder.initialScreen(InitialScreen.SIGN_UP)
            InitialScreen.FORGOT_PASSWORD -> lockBuilder.initialScreen(InitialScreen.FORGOT_PASSWORD)
        }

        lock = lockBuilder.build(this)
        startActivity(lock.newIntent(this@LoginActivity))
    }
```

```
private fun getLockBuilder(): Lock.Builder {
        return Lock.newBuilder(getAuth0Account(), lockCallback)
            .withScheme("demo")
            .withAudience(String.format("https://%s/api/v2/", getString(R.string.com_auth0_domain)))
            .withScope("openid profile email offline_access read:current_user update:current_user_metadata")
            .closable(true)
            .loginAfterSignUp(true)
            .withSignUpFields(getCustomFieldList())
            .allowedConnections(getConnections())
    }
```

```
private fun getCustomFieldList(): MutableList<CustomField> {
        val customFields: MutableList<CustomField> = ArrayList()

        val firstName = CustomField(
            R.drawable.ic_person,
            CustomField.FieldType.TYPE_NAME,
            Auth0Helper.UserMetadata.FIRST_NAME,
            R.string.hint_first_name)

        val lastName = CustomField(
            R.drawable.ic_person,
            CustomField.FieldType.TYPE_NAME,
            Auth0Helper.UserMetadata.LAST_NAME,
            R.string.hint_last_name)

        val mobile = CustomField(
            R.drawable.ic_phone,
            CustomField.FieldType.TYPE_NUMBER,
            Auth0Helper.UserMetadata.MOBILE,
            R.string.hint_mobile)

        customFields.add(firstName)
        customFields.add(lastName)
//        customFields.add(mobile)
        return customFields
    }
```

![image](https://user-images.githubusercontent.com/35893342/81059037-4be65100-8eed-11ea-8af9-0c2beb8a8ca1.png)

> - When I uncomment the mobile custom field, then it becomes as default one
>
> - I had checked through the library code and found some condition

i.e :
```
//  [SignUpFormView.java file]

MAX_FEW_CUSTOM_FIELDS = 2 is maintained in the Library

displayFewCustomFields = lockWidget.getConfiguration().getVisibleSignUpFields().size() <= MAX_FEW_CUSTOM_FIELDS;

if (displayFewCustomFields) {
        addCustomFields(configuration.getVisibleSignUpFields());
}
```
>
> - I debug that code & it's not working just because of the above code snippet
>
### Environment

> Please provide the following:

- **Version of this library used:2.18.0**

**Comment by lbalmaceda** [comment]
@amankumar367 The library's behavior is that if the amount of custom fields is greater than 2, they will be shown on a separate form after the user completes the email and username.

**Comment by sakthinath** [comment]
In iOS we have any restrictions for adding greater than 2 feilds.

**Comment by amankumar367** [comment]
@lbalmaceda Thanks for the update. But the same thing in iOS working for more than 2 custom fields.
>
>  Is it possible to be on the same SignUp screen because we need same screen in both environments(Android & iOS)? 
> If Yes, Please suggest me some solution otherwise I have to use the separate form
> 
> When separate form opened it look like below image
> - Does this form can be at the center?
> - Header text is coming even it's pass empty value
> - Same as in reset Password
>
![image](https://user-images.githubusercontent.com/35893342/81141195-8998b780-8f89-11ea-8754-1eeaf22b1ffd.png)

**Comment by lbalmaceda** [comment]
> Is it possible to be on the same SignUp screen because we need same screen in both environments(Android & iOS)?

We require to reduce the number of fields per page in order to have a form design that doesn't scroll. I understand that this is never an issue on a bigger screen but some of your users might not feel the same when it comes to smaller devices. I'll check with our iOS engineer what the iOS library behavior is. 

> Does this form can be at the center?
Yes, that's something that looks odd in the screenshot and that we can fix.

> Header text is coming even it's pass empty value

The header name here is shown since you're still on the sign-up form and the tabs, which provided context to the user, are no longer being shown. The user needs to know at all times when they are standing on. The title provides that in replacement of the tabs. Same for reset password.

What would have been your expectation here?

**Comment by amankumar367** [comment]
> What would have been your expectation here?

1. Should have some properties for Signup Custom Fields to make it in the single form as well as on separate form (It should be handle by Client)
2. Separate form should be at the center.

**Comment by lbalmaceda** [comment]
I'll bring up the discussion for (1) with the team but don't hold on that. Consider (2) will be done in the coming days.

**Comment by lbalmaceda** [comment]
We will add the setter choosing the number of custom fields to show on the first page. Stay tuned

**Comment by amankumar367** [comment]
> We will add the setter choosing the number of custom fields to show on the first page. Stay tuned

That would be great. Thanks

**Comment by lbalmaceda** [comment]
@amankumar367 you can check it before we merge it here #578

**Comment by amankumar367** [comment]
> @amankumar367 you can check it before we merge it here #578

I checked that, That's cool @lbalmaceda

**Comment by lbalmaceda** [comment]
2.20.0 will be published in 24hs
