### ISSUE TITLE
Showing SignIn Error during SignUp

### ISSUE THREAD

**Issue by amankumar367** [auth0/Lock.Android#579]
### Description

> When creating a user account. It's showing SignIn Error instead of SignUp Error
```
Getting Error: "THERE WAS AN ERROR PROCESSING THE SIGN IN"
Expected Error: "THERE WAS AN ERROR PROCESSING THE SIGN UP"
```

> Same for an existing user account. It should show `"THE USER ALREADY EXISTS"`
```
Getting Error: "THERE WAS AN ERROR PROCESSING THE SIGN IN"
Expected Error: "THE USER ALREADY EXISTS"
```

### Reproduction
> Enable Lock properties loginAfterSignUp(true)

```
Lock.newBuilder(Auth0, LockCallback)
            ...
            .loginAfterSignUp(true)
            ...
```
> It's working fine for new user account if this `loginAfterSignUp(false)` property is set as false. But same message for existing user account
```
For Existing User
Getting Error: "THERE WAS AN ERROR PROCESSING THE SIGN UP"
Expected Error: "THE USER ALREADY EXISTS"
```

> Check below screenshots
![photo_2020-05-16_10-18-42](https://user-images.githubusercontent.com/35893342/82877845-56c65b80-9f58-11ea-9bf1-11aeecb7d978.jpg)

### Environment
- **Version of this library used:2.19.0**

**Comment by sakthinath** [comment]
Same Issue iOS also Facing while signup using existing user it is showing something went wrong in SignUP .

If the user is not registered trying to login. Showing something went wrong in Login .

**Comment by lbalmaceda** [comment]
> When creating a user account. It's showing SignIn Error instead of SignUp Error

As you found out, this is the expected behavior when the "login after sign up" option is enabled. "Sign in" means "Sign Up + Log In". So basically, a new user is created and then that same user is logged in. If you need to change the message, you can always override the string resource.

> Same for an existing user account. It should show "THE USER ALREADY EXISTS"

This is that way to prevent user enumeration. You can read more about that on this [blog post](https://auth0.com/blog/balancing-ux-and-security-at-auth0/). I also suggest you read about a related tenant setting [here](https://auth0.com/docs/dashboard/reference/settings-tenant) (search for "enumeration")

**Comment by ruchi-dhore-tw** [comment]
@lbalmaceda I am getting same error when trying to sign up using email and password. However, if I use Sign up with Google, user gets added. This is the code snippet:

```
private fun loginNative() {
        lock = Lock.newBuilder(account, nativeCallback)
            .withScheme(getString(R.string.com_auth0_scheme))
            .withScope("openid profile email read:current_user update:current_user_metadata")
            .withAudience("https://${getString(R.string.com_auth0_domain)}/api/v2/")
            .closable(true)
            .setShowTerms(true)
            .setMustAcceptTerms(true)
            .build(this)

        startActivity(lock.newIntent(this))
    }
```

Are we missing anything?
