### ISSUE TITLE
Google Sign-In Button is transparent

### ISSUE THREAD

**Issue by morganlutz** [auth0/Lock.Android#581]
### Description

In [v2.18.0](https://github.com/auth0/Lock.Android/pull/563) the Google Sign-In button background logic was changed to support a white button with outlined background. However it appears that the drawable created for this is transparent, so in dark mode the button is black:

![google-sign-in](https://user-images.githubusercontent.com/11651971/85047780-27fe6800-b147-11ea-879a-ea0cd059a293.png)

### Reproduction

To reproduce, set the activity background theme color to something other than white. 

### Environment

- Library version: 2.20.0

This is the fix I put up in our fork: https://github.com/kiva/Lock.Android/pull/10/files. If you'd like, I can also make a PR here.

**Comment by lbalmaceda** [comment]
👋 thanks for reporting this @morganlutz. I'm thinking the issue could affect other providers, not just google. (I'd need to check). Let me give it a try on our side this week. If I reach the same solution I'll accept your PR. Cheers

**Comment by lbalmaceda** [comment]
@morganlutz Changes in that PR look good. 🙇  The only thing I'd ask you to keep is the `Auth0.Background` style, as it's being referenced [here](https://github.com/auth0/Lock.Android/blob/30b1beba0342aa27f817fd12ff1c4331130b3c2e/lib/src/main/java/com/auth0/android/lock/views/AuthConfig.java#L52) and someone else might also be overriding it on their apps.

**Comment by morganlutz** [comment]
Thanks @lbalmaceda. Will have a PR up soon.
