### ISSUE TITLE
Provision for apply activity theme programmatically. 

### ISSUE THREAD

**Issue by AndroidDev-Auction** [auth0/Lock.Android#586]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

> We can't change the theme colors using java files(programmatically). We always need to add XML styles for applying themes in the activity. 

### Describe the ideal solution

> We need to make some changes in access modifiers to access internal methods. We have made that change in the below-given pull request link. We thought it is necessary and we have some provision to update the theme programmatically/dynamic.

## Alternatives and current work-arounds

> For the workarounds we have created one pull request (https://github.com/auth0/Lock.Android/pull/585) for a fix. Can you please review this or if any change required then can you let us know?

### Additional context

> Here, We have fixed the same issue and this is a PR link. https://github.com/auth0/Lock.Android/pull/585

**Comment by lbalmaceda** [comment]
We want to keep that class private. Can you explain what issue you're facing when using XML files to set the attributes?

**Comment by AndroidDev-Auction** [comment]
Actually, I have a requirement like apply color dynamically using API given color. So with use of XML, it's not possible because as we all know XML is immutable, we can not change it runtime. So we want to make it as public and with use of that, we can set the color from .java file.

**Comment by lbalmaceda** [comment]
That class is meant to act as an internal helper, not to be public thus why I closed the PR. 

The reason we don't offer this dynamic theme option is that the style of the login widget is always associated with the same brand. Can you explain a bit further your scenario?  We never came across the use case of multiple brands in the same app, if that's what this is.

**Comment by lbalmaceda** [comment]
No, the android platform limits you to customize the theme right before calling `Activity#setContent()` when you launch the activity, in this case, that's happening on `LockActivity`. 

The builder methods to access the `Theme` were made private for some reason [before the GA](https://github.com/auth0/Lock.Android/pull/326) release. I imagine that enabling this back today is not just making a method public. It would involve reviewing that the correct style is being consumed everywhere, adding tests for that, etc. Currently, the only way to customize it is via the `styles.xml` resource file.

**Comment by lbalmaceda** [comment]
Closing this issue. Official support for a dynamic theme is not on the roadmap.
