### ISSUE TITLE
Page not found for callback URL

### ISSUE THREAD

**Issue by palimad** [auth0/Lock.Android#591]
On Nexus 6P device with 8.1.0 OS I get 
"Not Found" error when trying to sign up/sign in with Google. I am not able to sign up at all. On other devices same code works (Samsung S9, S7) Any idea what could be wrong? Regular flows with email/password works.

callback URL: https://zuchhtvdev.eu.auth0.com/android/sk.kosice.mobile.zuch/callback

On Samsung devices it redirects user to https://accounts.google.com/XXX page, on Nexus 6P it opens browser with callback URL

**Comment by palimad** [comment]
Suddenly signup/sign in stopped working also on Samsung device without changes to code, same behavior -> redirected to callback URL with Not Found error. Any ideas?

**Comment by palimad** [comment]
Different test app is also not working, this callback URL says "not found" https://zuchhtvdev.eu.auth0.com/android/com.hotovo.auth0test/callback?code=bOrx75jjQfAwy4T7&state=URUHp9272XO3rAeCholXpaN50gStbIUu64-quFEOMJo

This is URL which I was able to copy from webview where application got stucked after clicking on  "Sign up with Google"

**Comment by lbalmaceda** [comment]
👋  Are you using the `WebAuthProvider` class in all of the attempts you mentioned above?

**Comment by palimad** [comment]
I launch auth this way:

val lock = Lock.newBuilder(auth0, callback)
            .withScope("openid profile offline_access email")
            .withAudience("https://xxx/api")
            .loginAfterSignUp(true)
            .build(this)

startActivity(lock?.newIntent(this));

**Comment by lbalmaceda** [comment]
Your Lock launch code looks fine. You mentioned you were able to log in fine with username and password credentials but that it fails with Google. Try with other social providers to discard if this is an external issue or a setup issue. 

If you still can't log in, that means is a setup issue. What steps have you followed in order to set that up? e.g. these https://github.com/auth0/Lock.Android#usage ?

**Comment by hoang-ei** [comment]
it looks like all social logins do not work, tested Sign in with Apple and Google

In log I get this 

`E/LockActivity: Failed to authenticate the user: THERE WAS AN ERROR PROCESSING THE SIGN IN
    com.auth0.android.authentication.AuthenticationException: Could not verify the ID token`

**Comment by lbalmaceda** [comment]
The other issue mentions an error when validating the received credentials. I understand then that this callback error is no longer a problem and you were able to resolve it. I'll close this one then, and we can focus on the other topic.
