### ISSUE TITLE
Support Auth0 v2.0.0

### ISSUE THREAD

**Issue by VincentJoshuaET** [auth0/Lock.Android#605]

**Comment by lbalmaceda** [comment]
@VincentJoshuaET I've raised this internally and we're considering this upgrade.

**Comment by morganlutz** [comment]
@lbalmaceda in the Auth0.Android you announce that [v1 will receive important bug and security updates until May 2021](https://github.com/auth0/Auth0.Android/pull/460/files). After that it is no longer supported. However it appears you are not prioritizing this update for [Lock.Android](https://github.com/auth0/Auth0.Android/issues/446#issuecomment-768967568), yet which effectively means users of Lock will not receive important bug and security updates after May 2021. Is Lock.Android being deprecated?

**Comment by kevlil83** [comment]
@morganlutz thanks for your comment. Upon further reflection we agree that a 3 month SLA is too short of time. To start, we will update GH to 6+ months and reevaluate as needed. In regards to Lock.Android, updating that library is something we are currently assessing with plans to prioritize in the very near future. Hope that clarifies and please reach out should you have any more questions. Thanks!

**Comment by morganlutz** [comment]
Thanks @kevlil83. We are trying to figure out if we need to migrate our internal fork of `Lock.Android` before the auth0 v2 cut off date -- or if we can wait because your team will do it before the deadline. Pushing the deadline from 3mo to 6mo is very helpful for us, thanks! Any further information you can provide around timing helps with our own planning.

**Comment by lbalmaceda** [comment]
@VincentJoshuaET @morganlutz Over the last weeks, we have been working to bring support for the new Auth0 Android SDK into this library. Today, we've shipped the first release that includes that. You will find it on [Maven Central](https://search.maven.org/artifact/com.auth0.android/lock) under the tag `3.0.0` (might take a few minutes to appear).

Note that this release involves breaking changes. If you are migrating from v2, we've prepared a [Migration Guide](https://github.com/auth0/Lock.Android/blob/main/MIGRATION_GUIDE.md) document that should help you update the usage in your app. 

Please, try the new version and don't hesitate to create a new issue with feedback or any problem that you come across during the migration. Thanks!
