### ISSUE TITLE
Why is LockActivity locked to android:screenOrientation="portrait"?

### ISSUE THREAD

**Issue by VincentJoshuaET** [auth0/Lock.Android#634]
```
<!-- Auth0 Lock -->
<activity
    android:name="com.auth0.android.lock.LockActivity"
    android:exported="false"
    android:launchMode="singleTask"
    android:screenOrientation="portrait"
    android:theme="@style/Lock.Theme" />
<!-- Auth0 Lock End -->
```

My app supports tablets/landscape orientation, so right now I just added `tools:remove="android:screenOrientation"` to my manifest. But why is this needed by the library? Shouldn't the library consumer decide if he wants to lock the orientation?

**Comment by lbalmaceda** [comment]
You can use the `tools:remove` line or even replace with the value you prefer, but we don't give support to other orientations. The Lock widget implements a design that was made for screens used in portrait mode.

**Comment by margin555** [comment]
Hi is there any way to change the text colour of "Don't remember your password" without changing the entered email and password text colour?
overriding this value chage all the text colors (email color, password color, message color)
    <color name="com_auth0_lock_normal_text">#FF000000</color>

**Comment by lbalmaceda** [comment]
Closing as it's been answered. If you have follow-up questions, feel free to re-open.
