### ISSUE TITLE
MFA screen for sign up page does not work with password grant

### ISSUE THREAD

**Issue by kpritam** [auth0/Lock.Android#644]
Steps to reproduce:

- Enable one of the MFA option from auth0 dashboard
- Run password grant flow via mobile
- Click on sign up option
- Enter username and password
- Click on sign up button

Expected:

- Setup MFA screen should get displayed

Actual:

- Error gets displayed `THERE WAS AN ERROR PROCESSING THE SIGN IN`

Details explanation of the issue is available here: https://community.auth0.com/t/not-able-to-sign-up-using-email-and-password-for-embedded-login-for-android-mobile-sdk/84375

**Comment by poovamraj** [comment]
@kpritam before diving deep, I just wanted to ensure whether you have checked out our [Auth0.Android](https://github.com/auth0/Auth0.Android/) SDK which works with Universal Login. This should make all the setup much smoother.

**Comment by kpritam** [comment]
Yes @poovamraj, that is correct.
In our case, there are some limitations on using universal login due to some trade off's with UX. Hence we are exploring embedded login option using android.lock

**Comment by poovamraj** [comment]
@kpritam thanks for that, I just checked out the thread you shared. Let me go deeper into this and get back to you!

**Comment by poovamraj** [comment]
@kpritam currently multifactor authentication enrollment is not available in Lock.Android. I will discuss with my team about this and get back to you. Thanks for your patience

**Comment by kpritam** [comment]
Thank you @poovamraj for taking a look.
