### ISSUE TITLE
Update demo app to demonstrate logout from Google

### ISSUE THREAD

**Issue by glebPrischepa** [auth0/Lock.Android#648]
It is not clear how to properly logout the user from its Google account so that 
next time the user will be prompted to choose another account.

The use case is
1. The user uses Google account to sign in.
2. The user is prompted to choose an account.
3. The user chooses account and signs in
4. The user is signed in.
5. The user signs out.
6. The user wants to choose another Google account and clicks "Sign in with google"
7. The user is not prompted to choose account, previous account is used.

Expected result - the user is prompted to choose another account.

I found different recommendations how to logout from Google Account but none of them worked.
At the same time your demo app does not demonstrate correct approach.

Please, update your demo app to demonstrate how properly logout user from its Google account.

Thanks in advance

**Comment by poovamraj** [comment]
Hi @glebPrischepa,

Looks like Google requires `prompt` value to be `select_account` to show the account selector as mentioned [here](https://community.auth0.com/t/how-do-i-force-the-universal-login-to-allow-the-user-to-select-a-gmail-account/72655/11)

Have you tried passing this to `withAuthenticationParameters` as mentioned in the documentation, you can use this to 

> Additional Authentication parameters can be set to use with different Identity Providers.

**Comment by poovamraj** [comment]
@glebPrischepa Hope the above solution helped you. Please feel free to reopen this issue if you have more doubts.
