### ISSUE TITLE
Social Login - Google Plus(non native) fails to return from browser

### ISSUE THREAD

**Issue by ritdaw** [auth0/Lock.Android#69]
I'm using Lock 1.5 with Google plus and DB authentication. When tapping the G+ icon to login the default browser opens up. I tap the account I want to use but the page reloads and doesn't return to the app. I can see from the Auth0 console that authentication has been successful. What is the expected flow?

**Comment by hzalaz** [comment]
It will return from the browser to your application. Did you configure `LockActivity` intent filter properly?

Here is an example of how it should look:

```xml
  <intent-filter>
    <action android:name="android.intent.action.VIEW"/>
    <category android:name="android.intent.category.DEFAULT"/>
    <category android:name="android.intent.category.BROWSABLE"/>
    <data android:scheme="a0INSERT_YOUR_APP_CLIENT_ID" android:host="YOUR_ACCOUNT_DOMAIN"/>
  </intent-filter>
```
the value of `android:scheme` **MUST** be in lowercase.

**Comment by ritdaw** [comment]
I didn't have clientid in lowercase, mainly because it was copied from the auth0 console which isn't all in lowercase. I have just tried changing it but unfortunately it still doesn't return to the application. If you tap the google account again in the web browser it displays the "something went wrong!" error.

Am I missing something?

**Comment by hzalaz** [comment]
Yes, the lowercase shouldn't matter at all but the intent filters compares using case sensitive something it's case insensitive (the scheme).

That is the only configuration required to return to the app, Did you try our seed app from https://auth0.com/docs/quickstart/native-mobile/android/no-api? (You need to be logged in to download it with your credentials).

If you can send me your app to `support@auth0.com` and I'll take a look.

**Comment by ritdaw** [comment]
Just checking out the seed app again now.

**Comment by ritdaw** [comment]
Turns out it was related to the current activity ending when receiving the broadcast and therefore the browser remained at the top of the stack.

**Comment by hzalaz** [comment]
Good catch, Does `LockActivity` have `launchMode` set to `singleTask`?, otherwise it won't work when returning from the browser.

**Comment by ritdaw** [comment]
Yes it does. We end our preference activity (which is where auth0 login sits) when a successful login occurs because all handling after login including UI updates happen in a different activity.

**Comment by hzalaz** [comment]
Ok, odd that your preference activity doesn't have a parent but I am not familiar with your app :smile:.
Let me know if you need any more help (if everything is working please close the issue)

**Comment by ritdaw** [comment]
It's a launcher so has all sorts of odd complexities.
