### ISSUE TITLE
java.lang.NoClassDefFoundError: com.auth0.identity.WebIdentityProvider

### ISSUE THREAD

**Issue by mauriciocoelho** [auth0/Lock.Android#79]
Hello, 
for smaller api that 21 is the error occurring at the time of build. This occurred after adding dependency 'com.google.android.gms: play-services: 7.3.0' 

I used version 1.3.0, updated to the latest version 1.7 and

![capturar](https://cloud.githubusercontent.com/assets/5712300/7757263/68004cce-ffd7-11e4-8265-83af66750ca8.PNG)

**Comment by hzalaz** [comment]
@mauriciocoelho got this working Ok with API 19. 
What is the API level of the device you are testing with?. Also the Exception is in Runtime right?

If you can reproduce this issue in a small sample I'll take a look at it. Maybe try replicating part of your setup with our seed sample https://auth0.com/docs/quickstart/native-mobile/android/no-api.

**Comment by mauriciocoelho** [comment]
@hzalaz  removing the 'com.google.android.gms: play-services: 7.3.0' the Lock works normally.
only adicinoando dependence of the play-services7.3.0 generates this error.

**Comment by joaom182** [comment]
+1 This occurs on API 16

**Comment by hzalaz** [comment]
@mauriciocoelho Works for me in API 16 too.
Can you send me zip with a project that can reproduce this exception?
Is it a debug or release build?
Are you running proguard for that build? (That might explain the missing class)

**Comment by mauriciocoelho** [comment]
I think I'm


``` java
buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-project.txt'), 'proguard-rules.pro'
            proguardFile '../proguard/proguard-facebook.pro' //facebook native auth
            proguardFile '../proguard/proguard-google-play-services.pro' //G+ native auth
            proguardFile '../proguard/proguard-android-async-http.pro' //Auth0 core
            proguardFile '../proguard/proguard-jackson-2.pro' //Auth0 core
            proguardFile '../proguard/proguard-square-otto.pro' //Lock
            proguardFile '../proguard/proguard-lock.pro' //Lock
        }
    }
```

**Comment by hzalaz** [comment]
Well, for release you are (and should be) running Proguard, but if you run from IDE it will use debug instead (no minify). I've just tested the proguard configuration I have and is still working so unless you added something special in your proguard config I'm not sure whats wrong.

Can you try replicating this issue in our sample from docs and send it to me?

**Comment by mauriciocoelho** [comment]
I managed to solve the problem by downgrade to playservices 6.5.87, but after that I found that was multiDexEnabled = true. which led to other errors :( 

thank's for your time
