### ISSUE TITLE
G+ native auth should use the minimal scope

### ISSUE THREAD

**Issue by pmq** [auth0/Lock.Android#81]
I'm comparing the Android native and web Google OAuth integration, and found out that using the web integration, the user is asked to enable our app to access its profile and email (minimal requirements) and using the native integration, the user is asked for this + access to his/her G+ circles, posting app-related info to its "timeline".

Could the native auth be downgraded to using the bare minimum G+ scope?

Many thanks!

**Comment by hzalaz** [comment]
Fixed in version `2.0.0` of `com.auth0.android:lock-googleplus`
